Fuzzy/urls.py
from django.conf.urls import url, include
# from django.contrib import admin
from .views import ReadDatas, BatasanFuzzy, ProsesFuzzifikasi, FileDetail, CreateDatas, UpdateDatas, DeleteDatas

urlpatterns = [
  url(r'^data/$', ReadDatas, name='readdata'),
  url(r'^data/create/$', CreateDatas, name='create_datas'),
  url(r'^data/(?P<pk>\d+)/update/$', UpdateDatas, name='update_datas'),
  url(r'^data/(?P<pk>\d+)/delete/$', DeleteDatas, name='delete_datas'),

  url(r'^batasan/$', BatasanFuzzy, name='batasan'),
  url(r'^proses/$', ProsesFuzzifikasi, name='proses'),
  url(r'^detail/(?P<datas>[\w.+_-]+)/(?P<filename>[\w.+_-]+)/$', FileDetail, name='filedetail'),
]

History/urls.py
from django.conf.urls import url, include
# from django.contrib import admin
from .views import FileData, DetailFilename, FileDetail, DeleteHistory

urlpatterns = [
  url(r'^filename/$', FileData, name='filename'),
  url(r'^filename/(?P<id>[\w.+_-]+)/detail/$', DetailFilename, name='detailfilename'),
  url(r'^filename/(?P<id>[\w.+_-]+)/delete/$', DeleteHistory, name='deletefilename'),
  url(r'^detail/(?P<datas>[\w.+_-]+)/(?P<filename>[\w.+_-]+)/$', FileDetail, name='filedetail'),
]

tsukamoto/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.contrib.auth import views as auth_views
# from django.views.generic.base import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # to urls apps fuzzy
    url(r'^fuzzy/', include("Fuzzy.urls", namespace='Fuzzy')),
    url(r'^history/', include("History.urls", namespace='History')),
    
    url(r'^', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'logged_out.html'}, name='logout'),
]

History/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class FileName(models.Model):
	filename = models.CharField(max_length=30)

	def __str__(self):
		return '%s' % (self.id)

class Batas(models.Model):
	filename = models.ForeignKey('History.FileName', null = True, related_name = 'Filename_Batas')
	parameter = models.CharField(max_length=30) 
	derajat = models.CharField(max_length=30) 
	hasil = models.CharField(max_length=30)

	def __str__(self):
		return '%s' % (self.id)

History/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponse

from .models import FileName, Batas
from Fuzzy.models import Fuzzifikasi, RuleBase, Defuzzifikasi, FileDatas

# Create your views here.

def FileData(request):
	filename = FileName.objects.all()

	return render(request, "history.html", { 'filename' : filename })

def DetailFilename(request, id):
	getfilename = FileName.objects.get(id = id)
	fuzz = Fuzzifikasi.objects.filter(filename = getfilename.filename)
	rule = RuleBase.objects.filter(filename = getfilename.filename)
	defuzz = Defuzzifikasi.objects.filter(filename = getfilename.filename)
	filedatas = FileDatas.objects.filter(filename = getfilename.filename)
	batas = Batas.objects.filter(filename = getfilename)

	# Perhitungan Mape
	a = 0
	n = 0
	for b in defuzz:
		c = abs(b.datas.produksi - int(b.hasil))
		d = float(c) / float(b.datas.produksi)
		a = a + d
		n = n + 1
	mape =(a * 100) / float(n)
	akurasi = 100 - mape
	print a

	return render(request, "detail_history.html", {
		'fuzzifikasi' : fuzz,
		'rulebase' : rule,
		'defuzzifikasi': defuzz,
		'filedatas' : filedatas,
		'batas' : batas,
		'mape' : mape,
		'akurasi' : akurasi,
		})

def FileDetail(request, datas, filename):
	filedata = FileDatas.objects.get(id=filename)
	fuzz = Fuzzifikasi.objects.filter(datas=datas, filename=filedata.filename)
	rule = RuleBase.objects.filter(datas=datas, filename=filedata.filename)
	defuzz = Defuzzifikasi.objects.filter(datas=datas, filename=filedata.filename)

	return render(request, 'detail_history_data.html', {
		'fuzzifikasi' : fuzz,
		'rulebase' : rule,
		'defuzzifikasi': defuzz,
		})

def DeleteHistory(request, id):
	history = FileName.objects.get(id = id)

	defuzz = Defuzzifikasi.objects.filter(filename=history.filename).delete()
	filedatas = FileDatas.objects.filter(filename=history.filename).delete()
	fuzz = Fuzzifikasi.objects.filter(filename=history.filename).delete()
	rule = RuleBase.objects.filter(filename=history.filename).delete()
	history.delete()

	return FileData(request)

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Madur</title>

    <!-- Bootstrap -->
    <link href="{% static "vendors/bootstrap/dist/css/bootstrap.min.css" %}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% static "vendors/font-awesome/css/font-awesome.min.css" %}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{% static "vendors/nprogress/nprogress.css" %}" rel="stylesheet">
    <!-- jQuery custom content scroller -->
    <link href="{% static "vendors/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.min.css" %}" rel="stylesheet"/>
    <!-- iCheck -->
    <link href="{% static "vendors/iCheck/skins/flat/green.css" %}" rel="stylesheet">
    <!-- Datatables -->
    <link href="{% static "vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{% static "build/css/custom.min.css" %}" rel="stylesheet">
  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 left_col">
          <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a href="index.html" class="site_title"> <i class="fa fa-ils"></i> <span>Kripik Madur</span></a>
            </div>

            <div class="clearfix"></div>

            <!-- menu profile quick info -->
            <div class="profile clearfix">
              <div class="profile_pic">
                <img src="{% static "images/img.png" %}" alt="..." class="img-circle profile_img">
              </div>
              <div class="profile_info">
                <span>Selamat Datang,</span>
                <h2>Admin</h2>
              </div>
            </div>
            <!-- /menu profile quick info -->

            <br />

            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <h3>General</h3>
                <ul class="nav side-menu">
                  <li><a href="{% url 'Fuzzy:readdata' %}"><i class="fa fa-desktop"></i> Proses Data </a></li>
                  <li><a href="{% url 'Fuzzy:batasan' %}"><i class="fa fa-line-chart"></i> Proses Peramalan </span></a></li>
                  <li><a href="{% url 'History:filename' %}"><i class="fa fa-history"></i> History Peramalan </span></a></li>
                </ul>
              </div>
            </div>
            <!-- /sidebar menu -->
          </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">
          <div class="nav_menu">
            <nav>
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>

              <ul class="nav navbar-nav navbar-right">
                <li class="">
                  <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <img src="{% static "images/img.png" %}" alt="">Admin
                    <span class=" fa fa-angle-down"></span>
                  </a>
                  <ul class="dropdown-menu dropdown-usermenu pull-right">
                    <li><a href="{% url 'login' %}"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                  </ul>
                </li>

              </ul>
            </nav>
          </div>
        </div>
        <!-- /top navigation -->

        <!-- page content -->
        {% block content %}
        {% endblock %}
        <!-- /page content -->

        <!-- footer content -->
        <footer>
          <div class="pull-right">
            ©2018 Madur, by <a href="https://colorlib.com">Colorlib</a>
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
      </div>
    </div>

    <!-- jQuery -->
    <script src="{% static "vendors/jquery/dist/jquery.min.js" %}"></script>
    <!-- Bootstrap -->
    <script src="{% static "vendors/bootstrap/dist/js/bootstrap.min.js" %}"></script>
    <!-- FastClick -->
    <script src="{% static "vendors/fastclick/lib/fastclick.js" %}"></script>
    <!-- NProgress -->
    <script src="{% static "vendors/nprogress/nprogress.js" %}"></script>
    <!-- jQuery custom content scroller -->
    <script src="{% static "vendors/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js" %}"></script>
    <!-- iCheck -->
    <script src="{% static "vendors/iCheck/icheck.min.js" %}"></script>
    <!-- Datatables -->
    <script src="{% static "vendors/datatables.net/js/jquery.dataTables.min.js" %}"></script>
    <script src="{% static "vendors/datatables.net-bs/js/dataTables.bootstrap.min.js" %}"></script>
    <script src="{% static "vendors/datatables.net-buttons/js/dataTables.buttons.min.js" %}"></script>
    <script src="{% static "vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js" %}"></script>
    <script src="{% static "vendors/datatables.net-buttons/js/buttons.flash.min.js" %}"></script>
    <script src="{% static "vendors/datatables.net-buttons/js/buttons.html5.min.js" %}"></script>
    <script src="{% static "vendors/datatables.net-buttons/js/buttons.print.min.js" %}"></script>
    <script src="{% static "vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js" %}"></script>
    <script src="{% static "vendors/datatables.net-keytable/js/dataTables.keyTable.min.js" %}"></script>
    <script src="{% static "vendors/datatables.net-responsive/js/dataTables.responsive.min.js" %}"></script>
    <script src="{% static "vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js" %}"></script>
    <script src="{% static "vendors/datatables.net-scroller/js/dataTables.scroller.min.js" %}"></script>
    <script src="{% static "vendors/jszip/dist/jszip.min.js" %}"></script>
    <script src="{% static "vendors/pdfmake/build/pdfmake.min.js" %}"></script>
    <script src="{% static "vendors/pdfmake/build/vfs_fonts.js" %}"></script>

    <!-- Custom Theme Scripts -->
    <script src="{% static "build/js/custom.min.js" %}"></script>

    <script type="text/javascript">
      $(function () {

        var loadForm = function () {
          var btn = $(this);
          $.ajax({
            url: btn.attr("data-url"),
            type: 'get',
            dataType: 'json',
            beforeSend: function () {
              $("#modal-datas").modal("show");
            },
            success: function (data) {
              $("#modal-datas .modal-content").html(data.html_form);
            }
          });
        };

        var saveForm = function () {
          var form = $(this);
          $.ajax({
            url: form.attr("action"),
            data: form.serialize(),
            type: form.attr("method"),
            dataType: 'json',
            success: function (data) {
              if (data.form_is_valid) {
                $("#datas-table tbody").html(data.html_datas_list);
                $("#modal-datas").modal("hide");
              }
              else {
                $("#modal-datas .modal-content").html(data.html_form);
              }
            }
          });
          return false;
        };

        // Create book
        $(".js-create-datas").click(loadForm);
        $("#modal-datas").on("submit", ".js-datas-create-form", saveForm);

        // Update book
        $("#datas-table").on("click", ".js-update-datas", loadForm);
        $("#modal-datas").on("submit", ".js-datas-update-form", saveForm);

        // Delete book
        $("#datas-table").on("click", ".js-delete-datas", loadForm);
        $("#modal-datas").on("submit", ".js-datas-delete-form", saveForm);

      });
    </script>
    
    <script type="text/javascript">
      var modalDiv = $(".modal-div");
      console.log(modalDiv)

      $(".open-modal").on("click", function() {
        $.ajax({
          url: $(this).attr("data-url"),
          success: function(data) {
            modalDiv.html(data);
            $("#myEdit").modal();
          }
        });
      });
    </script>
  </body>
</html>

templates/detail_history_data.html
<div class="modal fade" tabindex="-1" role="dialog" aria-hidden="true" id = 'myEdit'>
	<div class="modal-dialog modal-lg">
		<div class="modal-content">

			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span></button>
				<h4 class="modal-title" id="myModalLabel">Detail Hasil</h4>
			</div>
			<div class="modal-body">
								<h3>Hasil Fuzzyfikasi</h3>
								<table class="table table-striped table-bordered">
			                      <thead>
			                        <tr>
			                          <th>Bulan</th>
			                          <th>Tanggal</th>
			                          <th>Variabel</th>
			                          <th>Himpunan Fuzzy</th>
			                          <th>Hasil</th>
			                        </tr>
			                      </thead>
			                      <tbody>
			                      {% for fuzz in fuzzifikasi %}
			                        <tr>
			                          <td>{{ fuzz.datas.bulan }}</td>
			                          <td>{{ fuzz.datas.minggu }}</td>
			                          <td>{{ fuzz.parameter }}</td>
			                          <td>{{ fuzz.derajat }}</td>
			                          <td>{{ fuzz.hasil }}</td>
			                        </tr>
			                      {% endfor %}
			                      </tbody>
			                    </table>
			                    <h3>Hasil Rule Base</h3>
		                         <table class="table table-bordered">
			                      <thead>
			                        <tr>
			                          <th>Bulan</th>
			                          <th>Tanggal</th>
			                          <th>Permintaan</th>
			                          <th>Persediaan</th>
			                          <th>a-predikat</th>
			                          <th>z</th>
			                          <th>a-predikat * z</th>
			                        </tr>
			                      </thead>
			                      <tbody>
			                      {% for rule in rulebase %}
			                        <tr>
			                          <td>{{ rule.datas.bulan }}</td>
			                          <td>{{ rule.datas.minggu }}</td>
			                          <td>{{ rule.permintaan }}</td>
			                          <td>{{ rule.persediaan }}</td>
			                          <td>{{ rule.a_predikat }}</td>
			                          <td>{{ rule.z }}</td>
			                          <td>{{ rule.az_predikat }}</td>
			                        </tr>
			                      {% endfor %}
			                      </tbody>
			                     </table>
			                     <h3>Hasil Defuzzyfikasi</h3>
			                     <table class="table table-bordered">
			                      <thead>
			                        <tr>
			                          <th>Bulan</th>
			                          <th>Tanggal</th>
			                          <th>Hasil</th>
			                        </tr>
			                      </thead>
			                      <tbody>
			                      {% for defuzz in defuzzifikasi %}
			                        <tr>
			                          <td>{{ defuzz.datas.bulan }}</td>
			                          <td>{{ defuzz.datas.minggu }}</td>
			                          <td>{{ defuzz.hasil }}</td>
			                        </tr>
			                      {% endfor %}
			                      </tbody>
			                     </table>
			</div>
			<div class="modal-footer">
					<button type="button" class="btn btn-primary" data-dismiss="modal">Tutup</button>
					<!-- <button type="button" class="btn btn-primary">Save changes</button> -->
			</div>
			
    	</div>
  	</div>
</div>

templates/history.html
{% extends 'base.html' %}
	{% block content %}
	    <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3>History Peramalan <small> (Permintaan, Persediaan, Produksi)</small></h3>
              </div>
              <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                  <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                      <button class="btn btn-default" type="button">Go!</button>
                    </span>
                  </div>
                </div>
              </div>
            </div>

	        <div class="row">
	            <div class="col-md-12 col-sm-12 col-xs-12">
	                <div class="x_panel">
	                  <div class="x_title">
	                    <h2>Open History<small>Admin</small></h2>
	                    <ul class="nav navbar-right panel_toolbox">
	                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
	                      <li><a class="close-link"><i class="fa fa-close"></i></a></li>
	                    </ul>
	                    <div class="clearfix"></div>
	                  </div>
	                  <div class="x_content">
	                    
	                    
	                        	
	                        	<div class="col-md-6 col-sm-6 col-xs-12">
		                        <table class="table table-bordered">
			                      <thead>
			                        <tr>
			                          <th>Filename</th>
			                          <th>Action</th>
			                        </tr>
			                      </thead>
			                      <tbody>
			                      {% for name in filename %}
			                        <tr>
			                          <td>{{ name.filename }}</td>
			                          <td>
			                          	<a class="btn btn-success btn-xs" href="{% url 'History:detailfilename' name.id %}">Detail peramalan</a>
			                          	<a href="{% url 'History:deletefilename' name.id %}" class="btn btn-danger btn-xs">Hapus</a></td>
			                        </tr>
			                      {% endfor %}
			                      </tbody>
			                    </table>
			                 	</div>
			                  
	                  </div>
	                </div>
	            </div>
	        </div>
	       </div>
        </div>
    {% endblock %}

templates/list_datas.html
{% extends 'base.html' %}
	{% block content %}
	    <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3>Tabel Data <small> (Permintaan, Persediaan, Produksi)</small></h3>
              </div>
              <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                  <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                      <button class="btn btn-default" type="button">Go!</button>
                    </span>
                  </div>
                </div>
              </div>
            </div>

	        <div class="row">
	            <div class="col-md-12 col-sm-12 col-xs-12">
	                <div class="x_panel">
	                  <div class="x_title">
	                    <h2>Tabel Data<small>Admin</small></h2>
	                    <ul class="nav navbar-right panel_toolbox">
	                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
	                      <li><a class="close-link"><i class="fa fa-close"></i></a></li>
	                    </ul>
	                    <div class="clearfix"></div>
	                  </div>
	                  	<!-- <div class="col-md-2 col-sm-2 col-md-offset-2"> -->
	                  		<button type="button" class="btn btn-success js-create-datas" data-url="{% url 'Fuzzy:create_datas' %}"> <span class="glyphicon glyphicon-plus"></span> Tambah Data </button>

	                  		<a href="{% url 'Fuzzy:batasan' %}" class="btn btn-primary"><span class="glyphicon glyphicon-stats"></span> Proses Peramalan </a>
	                  		<br>
	                  		<br>
	              		<!-- </div> -->
	                  <div class="x_content">
	                    
	                    <table id="datas-table" class="table table-bordered">
	                      <thead>
	                        <tr>
	                          <th>Bulan</th>
	                          <th>Tanggal</th>
	                          <th>Permintaan</th>
	                          <th>Persediaan</th>
	                          <th>Produksi</th>
	                          <th>Action</th>
	                        </tr>
	                      </thead>

	                      <tbody>
	                      {% include 'partial_datas_list.html' %}
	                      </tbody>
	                    </table>
	                  </div>
	                </div>
	            </div>
	        </div>
        	<div class="modal fade" id="modal-datas">
    		<div class="modal-dialog">
      			<div class="modal-content">
      			</div>
      		</div>
      		</div>
	       </div>
        </div>
    </div>
    {% endblock %}

templates/logged_out.html
 <h2>Logged out</h2>
  <p>You have been successfully logged out.</p>
  <p><a href="{% url 'login' %}">Log in</a> again.</p>

templates/login.html
<!-- 
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form> -->
  {% load staticfiles %}
  <!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Madur</title>

    <!-- Bootstrap -->
    <link href="{% static "vendors/bootstrap/dist/css/bootstrap.min.css" %}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% static "vendors/font-awesome/css/font-awesome.min.css" %}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{% static "vendors/nprogress/nprogress.css" %}" rel="stylesheet">
    <!-- Animate.css -->
    <link href="{% static "vendors/animate.css/animate.min.css" %}" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{% static "build/css/custom.min.css" %}" rel="stylesheet">
  </head>

  <body class="login">
    <div>
      <a class="hiddenanchor" id="signup"></a>
      <a class="hiddenanchor" id="signin"></a>

      <div class="login_wrapper">
        <div class="animate form login_form">
          <section class="login_content">
            <form>
              <h1>Login Admin</h1>
              <div>
                <input type="text" class="form-control" placeholder="Username" required="" />
              </div>
              <div>
                <input type="password" class="form-control" placeholder="Password" required="" />
              </div>
              <div>
                <a class="btn btn-default submit" href="{% url 'Fuzzy:readdata'%}">Log in</a>
                <a class="reset_pass" href="#">Lost your password?</a>
              </div>

              <div class="clearfix"></div>

              <div class="separator">
                <p class="change_link">Silakan Login
                </p>

                <div class="clearfix"></div>
                <br />

                <div>
                  <h1><i class="fa fa-area-chart"></i> Keripik Singkong Madur</h1>
                  <p>©2018
                </div>
              </div>
            </form>
          </section>
        </div>

        
      </div>
    </div>
  </body>
</html>

templates/modal_create_datas.html
{% load widget_tweaks %}

  <form method="post" action="{% url 'Fuzzy:create_datas' %}" class="js-datas-create-form">
    {% csrf_token %}
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h4 class="modal-title">Tambah Data</h4>
    </div>
    <div class="modal-body">
      {% include 'modal_form.html' %}
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      <button type="submit" class="btn btn-primary">Tambah Data</button>
    </div>
  </form>

templates/modal_delete.html
<form method="post" action="{% url 'Fuzzy:delete_datas' datas.id %}" class="js-datas-delete-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Hapus Data</h4>
  </div>
  <div class="modal-body">
    <h4>Hapus Data Bulan <strong>{{ datas.bulan }} </strong>, Tanggal <strong>{{ datas.minggu }}</strong> ?</h4>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-danger">Delete Data</button>
  </div>
</form>

templates/modal_form.html
{% load widget_tweaks %}

{% for field in form %}
  <div class="form-group{% if field.errors %} has-error{% endif %}">
    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
    {% render_field field class="form-control" %}
    {% for error in field.errors %}
      <p class="help-block">{{ error }}</p>
    {% endfor %}
  </div>
{% endfor %}

templates/modal_update_datas.html
<form method="post" action="{% url 'Fuzzy:update_datas' form.instance.pk %}" class="js-datas-update-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Edit data</h4>
  </div>
  <div class="modal-body">
    {% include 'modal_form.html' %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Edit data</button>
  </div>
</form>

templates/partial_datas_list.html
						{% for data in datas %}
	                        <tr>
	                          <td>{{ data.bulan }}</td>
	                          <td>{{ data.minggu }}</td>
	                          <td>{{ data.permintaan }}</td>
	                          <td>{{ data.persediaan }}</td>
	                          <td>{{ data.produksi }}</td>
	                          <td>
	                          	<button type="button" class="btn btn-warning btn-xs js-update-datas" 
	                          	data-url="{% url 'Fuzzy:update_datas' data.id %}">
	                          	<span class="glyphicon glyphicon-pencil"></span> Edit </button> 
	                          	<button type="button" class="btn btn-danger btn-xs js-delete-datas"
	                          	data-url="{% url 'Fuzzy:delete_datas' data.id %}">
	                          	<span class="glyphicon glyphicon-trash"></span> Delete </button>
	                      	  </td>
	                        </tr>
	                      {% endfor %}